[package]
name = "bevy_asset_loader"
version = "0.11.0-github.main"
authors = ["Niklas Eicker <git@nikl.me>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Bevy plugin for asset loading"
repository = "https://github.com/NiklasEi/bevy_asset_loader"
homepage = "https://github.com/NiklasEi/bevy_asset_loader"
documentation = "https://docs.rs/bevy_asset_loader"
keywords = ["bevy", "gamedev", "asset", "assets"]
categories = ["game-development"]
readme = "../README.md"

[features]
# This feature adds support for bevy's TextureAtlas assets
2d = [
    "bevy/bevy_sprite",
    "bevy_asset_loader_derive/2d",
]
# This feature adds support for bevy's StandardMaterial assets
3d = [
    "bevy/bevy_pbr",
    "bevy_asset_loader_derive/3d",
]
dynamic_assets = ["bevy_asset_ron", "serde"]
progress_tracking = ["bevy_loading"]

[dependencies]
bevy = { version = "0.7", default-features = false }
bevy_asset_loader_derive = { version = "=0.11.0-github.main", path = "../bevy_asset_loader_derive" }
bevy_asset_ron = { version = "0.4", optional = true }
serde = { version = "1", optional = true }
#bevy_loading = { path = "../../bevy_loading", optional = true }
bevy_loading = { git = "https://github.com/NiklasEi/bevy_loading", branch = "simplify_ordering", optional = true }

[dev-dependencies]
bevy = { version = "0.7", features = ["vorbis"] }
bevy_loading = { git = "https://github.com/NiklasEi/bevy_loading", branch = "simplify_ordering" }
trybuild = "1.0"

[[example]]
name = "two_collections"
path = "examples/two_collections.rs"

[[example]]
name = "atlas_from_grid"
path = "examples/atlas_from_grid.rs"
required-features = ["2d"]

[[example]]
name = "init_resource"
path = "examples/init_resource.rs"

[[example]]
name = "dynamic_asset"
path = "examples/dynamic_asset.rs"

[[example]]
name = "dynamic_asset_ron"
path = "examples/dynamic_asset_ron.rs"
required-features = ["2d", "dynamic_assets"]

[[example]]
name = "no_loading_state"
path = "examples/no_loading_state.rs"

[[example]]
name = "standard_material"
path = "examples/standard_material.rs"
required-features = ["3d"]

[[example]]
name = "progress_tracking"
path = "examples/progress_tracking.rs"
required-features = ["progress_tracking"]
