[package]
name = "bevy_asset_loader"
version = "0.2.1"
authors = ["Niklas Eicker <git@nikl.me>"]
edition = "2018"
license = "MIT"
description = "Bevy plugin for asset loading"
repository = "https://github.com/NiklasEi/bevy_asset_loader"
homepage = "https://github.com/NiklasEi/bevy_asset_loader"
documentation = "https://docs.rs/bevy_asset_loader"
keywords = ["bevy", "gamedev", "asset", "assets"]
categories = ["game-development"]
readme = "../README.md"

[dependencies]
bevy = { version = "0.5.0", default-features = false }
bevy_asset_loader_derive = { version = "=0.2.1", path = "../bevy_asset_loader_derive" }

[dev-dependencies]
bevy = { version = "0.5.0", features = ["vorbis"] }

[[example]]
name = "two_collections"
path = "examples/two_collections.rs"
