[package]
name = "bevy_asset_loader"
version = "0.8.0"
authors = ["Niklas Eicker <git@nikl.me>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Bevy plugin for asset loading"
repository = "https://github.com/NiklasEi/bevy_asset_loader"
homepage = "https://github.com/NiklasEi/bevy_asset_loader"
documentation = "https://docs.rs/bevy_asset_loader"
keywords = ["bevy", "gamedev", "asset", "assets"]
categories = ["game-development"]
readme = "../README.md"

[features]
# This feature requires bevy's TextureAtlas and StandardMaterial assets to be available ("bevy/render")
render = ["bevy_asset_loader_derive/render"]

[dependencies]
bevy = { version = "0.6", default-features = false }
bevy_asset_loader_derive = { version = "=0.8.0", path = "../bevy_asset_loader_derive" }

[dev-dependencies]
bevy = { version = "0.6", features = ["vorbis"] }
trybuild = "1.0"

[[example]]
name = "two_collections"
path = "examples/two_collections.rs"

[[example]]
name = "atlas_from_grid"
path = "examples/atlas_from_grid.rs"
required-features = ["render"]

[[example]]
name = "init_resource"
path = "examples/init_resource.rs"

[[example]]
name = "dynamic_asset"
path = "examples/dynamic_asset.rs"

[[example]]
name = "color_material"
path = "examples/standard_material.rs"
required-features = ["render"]
